### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by YCG09** [jacklxc/ScientificDiscourseTagging#1]
您好，请问您在性能优化方面有什么建议吗？我测了一下处理一个case需要1秒

**Comment by jacklxc** [comment]
你可以试试看调一下batch_size, 不过不排除会出现爆显存的情况。主要性能瓶颈是keras_bert，你可以在bert_generator里调一调。如果有意再开发更好的模型建议用Huggingface+Pytorch，比老旧的Keras+Tensorflow 1.x好调试很多。

**Comment by YCG09** [comment]
好的，谢谢您的建议，不知道bert4keras相比于keras_bert是否会更快一些

**Comment by jacklxc** [comment]
其实我这里的BERT只是提供特征向量，没有fine-tune。你完全可以用任何好用的方法，比如直接用Huggingface TensorFlow的版本。不过TF的版本可能会有冲突，需要你自己debug一下。

**Comment by jacklxc** [comment]
我写这个模型的时候BERT才刚刚出现没多久，好用的package不多。现在就没必要坚持用Keras了。

**Comment by YCG09** [comment]
明白，我试着重构一下吧，谢谢！这个项目思想非常好，对我很有价值
