### ISSUE TITLE
Number of threads not being closed

### ISSUE THREAD

**Issue by ajjimeno** [jacklxc/ScientificDiscourseTagging#3]
I have been using a trained model to annotate a larger number of abstracts but I see that after some time, there is a large number of threads that are not being closed. It happens when I run it on a CPU or GPU. Are you aware of any solution for this problem?

**Comment by jacklxc** [comment]
Sorry, I've never encountered such a problem. Perhaps making sure you use the same environment as I did helps.

**Comment by ajjimeno** [comment]
Thanks Xiangci. I had the problem on several machines using the set up
mentioned on the website. I have tried TensorFlow 1.14 on several machines
and the problem disappeared.

  Best regards,
  Antonio
