### ISSUE TITLE
clause_parser

### ISSUE THREAD

**Issue by Shiyun-W** [jacklxc/ScientificDiscourseTagging#4]
Hi, I am new to syntax analysis, I would like to ask how to extract the clauses from the sentences. I tried the Stanford Parser, but it can only get the syntax tree of the sentence, Do I need to extract the cluase from the tree by myself? Or if there is any tool that could extract the clauses directly?

This is very important for my research, hope anyone could help me to reply this question, I would be very very appreciate!

**Comment by jacklxc** [comment]
It's been a while for me, and I don't clearly remember how I did it anymore. Perhaps my coauthor worked on the sentence split.

If I were you, I'd try this: https://stanfordnlp.github.io/CoreNLP/ssplit.html

**Comment by Shiyun-W** [comment]
I will try it. Thank you very much!
